# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "system_modules/desktop/silverblue/usr/share/gnome-shell/extensions/tilingshell@ferrarodomenico.com"
        versions: "16.2.0"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
