[OpenWebStart]
image=docker.io/library/ubuntu:24.04
additional_packages="curl git vim openjdk-8-jdk"

additional_flags="--env OWS_INSTALL=OpenWebStart_linux_1_14_0.deb"
additional_flags="--env OWS_VERSION=v1.14.0"
init_hooks="curl -L -O --output-dir /tmp/ https://github.com/karakun/OpenWebStart/releases/download/\${OWS_VERSION}/\${OWS_INSTALL}"
init_hooks="sudo apt-get install /tmp/\${OWS_INSTALL}"
init_hooks="sudo sed --in-place='.bak' '\''/^jdk.jar.disabledAlgorithms=.*$/,/^.*[^\]$/d'\'' /etc/java-8-openjdk/security/java.security"
init_hooks="sudo sed --in-place='.bak' '\''/^jdk.tls.disabledAlgorithms=.*$/,/^.*[^\]$/d'\'' /etc/java-8-openjdk/security/java.security"
# Start Line ADDR   - /^jdk.jar.disabledAlgorithms=.*$/
# ADDR Range        - /,/
# Stop Line ADDR    - /^.*[^\]$/
# Command           - /d

exported_apps="/usr/share/applications/itw-settings.desktop"
exported_apps="/usr/share/applications/javaws.desktop"
exported_bins="/usr/local/bin/itw-settings"
exported_bins="/usr/local/bin/javaws"
